### ISSUE TITLE
Support for HTTP authentication

### ISSUE THREAD

**Issue by cybrox** [mylisabox/flutter_mjpeg#17]
Hi, thanks for providing this project!

I've tested the streamer and it works very well with a simple MJPEG feed.

Do you have any plans to include support for HTTP Basic or even HTTP Digest authentication in the future?

**Comment by jaumard** [comment]
Hello, 
Never needed it but Basic is already supported as you can specify headers to the widgets. I don't know what HTTP Digest authentication is but if it's based on headers it's by default supported I guess. Have you tested `headers` field?

**Comment by cybrox** [comment]
Oh, sorry, I did not realize that I can pass headers as an argument. :facepalm: 

I somehow just assumed the list of options in the [README](https://pub.dev/packages/flutter_mjpeg#api) was exhaustive.
I'll do some testing and re-open if there's still something that does not work.

**Comment by jaumard** [comment]
It should be exhaustive but look like it need an update :D thanks for the report!
