### ISSUE TITLE
Pause the player

### ISSUE THREAD

**Issue by HedgeHao** [mylisabox/flutter_mjpeg#30]
Can I pause and resume the player?

**Comment by cybrox** [comment]
I don't think there's a way to pause the player directly but you can wrap it in a stateful widget and change the `isLive` value in its state, which should cause it to re-build.

When `isLive` is set to true, it will continuously fetch frames and "play". When `isLive` is set to false, it will fetch the latest frame once and then stay at that ("paused") until it is re-built.

**Comment by jaumard** [comment]
Yes `isLive` is here to support pause/resume action so please use that
