### ISSUE TITLE
How to capture a frame and save it as image file?

### ISSUE THREAD

**Issue by pluzmedia** [mylisabox/flutter_mjpeg#32]
Hi,
Is it possible to capture a frame and save it as image file?

**Comment by jaumard** [comment]
Hi,

You can use the `preprocessor` field to get the frame and do whatever you want with it.

**Comment by pluzmedia** [comment]
Hi,

Thanks for your reply. Could you share me sample code?

**Comment by cybrox** [comment]
Hi @pluzmedia, [this issue](https://github.com/mylisabox/flutter_mjpeg/issues/27) had the exact same goal.

You should find example code and some more information on this topic there.
