### ISSUE TITLE
framerate

### ISSUE THREAD

**Issue by taf2** [mylisabox/flutter_mjpeg#5]
It seems like the frame rate is very slow on iOS - like maybe 1 frame per 10 seconds or 1 frame per 20 seconds.  Any ideas on how to improve that?

```dart
 children: <Widget>[
            Expanded(
              child: Center(
                child: Mjpeg(
                  isLive: true,
                  stream: 'http://192.168.2.57/stream.mjpg'
                ),
              ),
            ),
          ],
```

**Comment by jaumard** [comment]
No the only thing that can change the frame rate is the network speed. The package doesn't do much itself except recreate the images.
Maybe you can improve the frame rate by lowering the resolution of the stream.

**Comment by taf2** [comment]
Thanks!   Yeah it's interesting connecting over the web browser on the same network it's nearly realtime but over the flutter app it's very slow...   I've lowered the frame rate and resolution will continue to experiment :)

**Comment by jaumard** [comment]
also you need to try your flutter app on production mode and not debug mode as it really slow for debug

**Comment by taf2** [comment]
Ah - I bet it's debug mode!

**Comment by dubbelpunt** [comment]
Hi, I have a similar frame rate problem when I put the stream behind a reverse proxy from nginx.
Example:
http://ip_ipcam/videostream.cgi ==> works perfect.

http://ip_server/ipcam1
nginx conf on ip_server:
location /ipcam1 {
    proxy_pass http://ip_ipcam/videostream.cgi
}
This works very slow, frame rate like taf2 commented. Via a browser, it works as expected, without interruptions.

Are you familiar with this issue? Any ideas?

**Comment by jaumard** [comment]
No I never used it behind a reverse proxy, but from the package point of view it shouldn't change anything as data is totally the same...

**Comment by dubbelpunt** [comment]
OK, maybe a dart bug? I will create a topic there.
Thanks!

**Comment by dubbelpunt** [comment]
After further investigation, I noticed that it is an Nginx reverse proxy issue. With an Apache reverse proxy it worked perfect.

**Comment by jaumard** [comment]
Good to know ! Thanks for the follow up :)
